In [ ]:
import xml.etree.ElementTree as ET
from pathlib import Path
import pandas as pd
import json
import requests
import re

WORKFLOW = Path.cwd().parent
DATA = WORKFLOW / "data"
RESULTS = WORKFLOW / "results"

master_file = pd.read_csv(DATA / "sheet1.csv", skiprows=2, low_memory=False)

genome_loc = pd.read_csv(DATA / "sheet2.csv")

genome_loc["snp"] = ''

for index, row in genome_loc.iterrows():
    genome_loc.at[index, "snp"] = (
        f"{row['position']}_{row['reference_nucleotide']}_{row['alternative_nucleotide']}"
    )

genome_loc = genome_loc.drop(
    columns=["reference_nucleotide", "chromosome", "alternative_nucleotide", "position"]
)

genome_loc.head()

          variant      snp
0  dnaA_p.Asp3Ala  8_AT_CA
1  dnaA_p.Asp3Ala    8_A_C
2  dnaA_p.Asp3Ala  8_AT_CC
3  dnaA_p.Asp3Ala  8_AT_CG
4  dnaA_p.Asp4His   10_G_C

In [ ]:
for index, row in master_file.iterrows():
    master_file.at[index,"FINAL CONFIDENCE GRADING"] = row["FINAL CONFIDENCE GRADING"][0]

master_file = master_file.loc[
    (master_file["FINAL CONFIDENCE GRADING"] == "1")
    | (master_file["FINAL CONFIDENCE GRADING"] == "2")
]

master_file = master_file[
    [
        "variant",
        "drug",
        "FINAL CONFIDENCE GRADING"
    ]
]

master_file.head()

              variant         drug FINAL CONFIDENCE GRADING
430      eis_c.-14C>T     Amikacin                        2
888     rrs_n.1401A>G     Amikacin                        1
890     rrs_n.1402C>T     Amikacin                        2
940     rrs_n.1484G>T     Amikacin                        1
2198  atpE_p.Ala63Pro  Bedaquiline                        2

In [ ]:
master_file = pd.merge(master_file, genome_loc, on="variant", how='inner')
master_file.head()

In [ ]:
'''
weight_dict = {i:{snp:0 for snp in master_file['snp'].unique()} for i in master_file['drug'].unique()}

for key, value in weight_dict.items():
    subset = master_file[master_file['drug'] == key]
    for index, row in subset.iterrows():
        weight_dict[row['drug']][row['snp']] = 1 
'''
        
weight_dict = {}

for _, row in master_file.iterrows():
    drug = row["drug"]
    snp = row["snp"]

    weight_dict.setdefault(drug, {})[snp] = 1

weight_dict

{'Amikacin': {'2715344_GTG_ATA': 1,
  '2715345_TG_CA': 1,
  '2715346_G_A': 1,
  '2715346_GGC_AGG': 1,
  '1473246_A_G': 1,
  '1473247_C_T': 1,
  '1473329_G_T': 1},
 'Bedaquiline': {'1461231_GCA_CCG': 1,
  '1461231_G_C': 1,
  '1461231_GCA_CCC': 1,
  '1461231_GCA_CCT': 1,
  '1461127_AC_CT': 1,
  '1461127_AC_CA': 1,
  '1461127_AC_CG': 1,
  '1461127_A_C': 1,
  '1461125_TGA_GGG': 1,
  '1461127_A_G': 1,
  '1461127_AC_GT': 1,
  '1461127_AC_GA': 1,
  '1461127_AC_GG': 1,
  '1461127_AC_TA': 1,
  '1461127_AC_TT': 1,
  '1461127_AC_TG': 1,
  '1461127_A_T': 1,
  '1461227_G_C': 1,
  '1461227_G_T': 1,
  '1461242_C_G': 1,
  '2859292_TGGGTCTCCTACAGAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAG_T': 1,
  '2859294_GGTCTCCTACAGAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACC_G': 1,
  '2859295_GTCTCCTACAGAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAG_G': 1,
  '2859303_CAGAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACA_C': 1,
  '2859303_CAG_TTA': 1,
  '2859303_CAG_C': 1,
  '2859303_CAG_TCA': 1,
  '2859304_AG_TA': 1,
  '2859305_GAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCC_G': 1,
  '2859306_AAT_CTA': 1,
  '2859306_AAT_TTA': 1,
  '2859306_AAT_TCA': 1,
  '2859306_A_ATAACG': 1,
  '2859308_TGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGT_T': 1,
  '2859308_TG_T': 1,
  '2859309_GGC_TTA': 1,
  '2859309_GGC_TCA': 1,
  '2859309_G_GT': 1,
  '2859309_GGC_CTA': 1,
  '2859310_G_GACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTC': 1,
  '2859312_CAG_TCA': 1,
  '2859312_CAG_TTA': 1,
  '2859313_AG_TA': 1,
  '2859313_A_AG': 1,
  '2859315_TTC_CTA': 1,
  '2859315_T_TCG': 1,
  '2859316_TC_CA': 1,
  '2859317_C_A': 1,
  '2859318_TTT_CTA': 1,
  '2859319_TT_CA': 1,
  '2859320_T_A': 1,
  '2859321_GGG_TCA': 1,
  '2859321_GGG_CTA': 1,
  '2859321_GGG_TTA': 1,
  '2859324_GA_TC': 1,
  '2859324_GA_CT': 1,
  '2859324_GA_TT': 1,
  '2859326_ACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCACCAAGTCGGTCAGCGCGGCAT_A': 1,
  '2859327_CCG_TTA': 1,
  '2859327_CCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACA_C': 1,
  '2859327_CCG_TCA': 1,
  '2859328_CG_TA': 1,
  '2859328_CGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCAC_C': 1,
  '2859330_GGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTG_G': 1,
  '2859330_GGT_CTA': 1,
  '2859330_GGT_TCA': 1,
  '2859330_GGT_TTA': 1,
  '2859332_TC_T': 1,
  '2859333_CA_TC': 1,
  '2859333_CA_TT': 1,
  '2859334_A_T': 1,
  '2859335_ACAATTCCGGGGTCTGCCCGGCG_A': 1,
  '2859336_CA_TT': 1,
  '2859336_CA_TC': 1,
  '2859337_A_T': 1,
  '2859337_AATTCCGG_A': 1,
  '2859339_TTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCC_T': 1,
  '2859339_TTC_CTA': 1,
  '2859340_TC_T': 1,
  '2859340_TC_CA': 1,
  '2859341_CCG_C': 1,
  '2859341_C_A': 1,
  '2859342_CGG_C': 1,
  '2859342_CGG_TCA': 1,
  '2859342_CGG_TTA': 1,
  '2859343_GG_TA': 1,
  '2859345_GGT_TTA': 1,
  '2859345_GGTCT_G': 1,
  '2859345_GGT_TCA': 1,
  '2859345_G_GGC': 1,
  '2859345_GGT_CTA': 1,
  '2859347_T_TGC': 1,
  '2859348_C_CCGGCGCGG': 1,
  '2859348_CTG_C': 1,
  '2859348_CTG_TCA': 1,
  '2859348_CT_C': 1,
  '2859348_CTG_TTA': 1,
  '2859349_TGC_T': 1,
  '2859350_G_GAT': 1,
  '2859350_G_A': 1,
  '2859350_G_GATCCTGTC': 1,
  '2859351_CCC_TTA': 1,
  '2859351_CCC_TCA': 1,
  '2859352_CC_TA': 1,
  '2859353_CGG_C': 1,
  '2859354_GGC_TTA': 1,
  '2859354_G_GCGGGT': 1,
  '2859354_GGC_TCA': 1,
  '2859354_GGCGGTTTCAGGCATTT_G': 1,
  '2859354_GGCGGTTTCAGGCAT_G': 1,
  '2859354_GGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTC_G': 1,
  '2859354_GGC_CTA': 1,
  '2859355_GC_G': 1,
  '2859355_GCGGTTTCAGGC_G': 1,
  '2859356_C_CTGATGATGCT': 1,
  '2859357_GGT_TTA': 1,
  '2859357_GGT_TCA': 1,
  '2859357_GGTTT_G': 1,
  '2859357_GGTTTC_G': 1,
  '2859357_GGT_CTA': 1,
  '2859357_GGTTTCAGGCATTTT_G': 1,
  '2859358_G_GA': 1,
  '2859358_GT_G': 1,
  '2859359_T_TAC': 1,
  '2859359_T_TAG': 1,
  '2859359_TTTCA_T': 1,
  '2859359_T_TCCGC': 1,
  '2859359_TTTCAGGC_T': 1,
  '2859359_TTTCAG_T': 1,
  '2859360_TTCAG_T': 1,
  '2859360_TTC_CTA': 1,
  '2859360_TTCAGGCATTTTCG_T': 1,
  '2859361_T_TCCCGC': 1,
  '2859361_TC_CA': 1,
  '2859362_C_A': 1,
  '2859362_C_CTG': 1,
  '2859362_C_CG': 1,
  '2859362_CAGGCA_C': 1,
  '2859363_AGG_CTA': 1,
  '2859363_AGG_TCA': 1,
  '2859363_AGG_TTA': 1,
  '2859363_AGGCATTTTCG_A': 1,
  '2859364_G_GCCGAGCTGTACCAGGCCGACCT': 1,
  '2859364_GGCATTTTC_G': 1,
  '2859365_GCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGC_G': 1,
  '2859365_GCATT_G': 1,
  '2859366_CATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCA_C': 1,
  '2859366_CATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCACCAAGTCGGTCAGCGCGGCATCGGCTGCTTCGCAGGCTAGTCGCAGCAGCGCCAGCTCGCCGGCGTCTTTAACCTCGCGCAGTGACTCCACAGTTCCGGATGCCCGCACCAACTCGGTGTTCTTGCCCTCCAGCGCGCCCGCCAAGGCGTCCAGGCCGTCCACCGTGACCACGTGGCTCTCGAAGCCCAGCTTTCCCACGCCGGCCTCGCCGGCCCGGCCGGCCAGGTAGCGCCCGACCGCGCGCTCGATAGCCACTTCGAGGTCGGGCGCTTGCGAGGCGGCCTGAGTGCGGTACCGGCCGT_C': 1,
  '2859366_CAT_TTA': 1,
  '2859366_CATTTT_C': 1,
  '2859366_CATTT_C': 1,
  '2859366_CATTTTCGG_C': 1,
  '2859366_CAT_TCA': 1,
  '2859367_ATT_A': 1,
  '2859367_ATTTTC_GCCG': 1,
  '2859367_ATTTTCGGCGTC_A': 1,
  '2859367_AT_TA': 1,
  '2859368_TTTTCGGCGTC_T': 1,
  '2859368_T_TCGGCAGC': 1,
  '2859368_TTTTCGGCG_T': 1,
  '2859369_TTTCGGCGTCC_T': 1,
  '2859369_TTT_CTA': 1,
  '2859370_T_TG': 1,
  '2859370_TT_CA': 1,
  '2859371_T_A': 1,
  '2859371_T_TC': 1,
  '2859372_CG_C': 1,
  '2859372_CGG_TCA': 1,
  '2859372_CGG_TTA': 1,
  '2859372_C_CCG': 1,
  '2859373_GGCGTC_G': 1,
  '2859373_GG_TA': 1,
  '2859374_G_GC': 1,
  '2859374_GC_G': 1,
  '2859375_CG_C': 1,
  '2859375_CGT_TTA': 1,
  '2859375_CGT_TCA': 1,
  '2859375_CGT_C': 1,
  '2859376_GTC_G': 1,
  '2859376_GTCCC_G': 1,
  '2859376_GT_TA': 1,
  '2859377_T_TTGTAGACG': 1,
  '2859378_CCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCG_C': 1,
  '2859378_C_CT': 1,
  '2859378_CCC_TTA': 1,
  '2859378_CCC_TCA': 1,
  '2859379_CC_TA': 1,
  '2859379_C_CACCA': 1,
  '2859379_C_CA': 1,
  '2859380_CGCCAG_C': 1,
  '2859380_CGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGT_C': 1,
  '2859381_GCC_TTA': 1,
  '2859381_GCC_TCA': 1,
  '2859381_GC_G': 1,
  '2859381_GCC_G': 1,
  '2859381_GCCAGC_G': 1,
  '2859381_GCC_CTA': 1,
  '2859382_C_CT': 1,
  '2859383_CA_C': 1,
  '2859384_A_AG': 1,
  '2859384_AGC_CTA': 1,
  '2859384_A_AC': 1,
  '2859384_AGC_TCA': 1,
  '2859384_A_AACGCTGCTGTACCACG': 1,
  '2859384_AGC_TTA': 1,
  '2859384_AG_A': 1,
  '2859385_GCC_G': 1,
  '2859385_G_GT': 1,
  '2859386_CCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCG_C': 1,
  '2859386_CCACTACCAAT_C': 1,
  '2859387_CAC_TTA': 1,
  '2859387_CAC_TCA': 1,
  '2859388_AC_TA': 1,
  '2859388_ACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTT_A': 1,
  '2859390_TAC_CTA': 1,
  '2859391_AC_TA': 1,
  '2859391_AC_CA': 1,
  '2859393_CA_TC': 1,
  '2859393_CA_TT': 1,
  '2859394_A_T': 1,
  '2859395_ATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACC_A': 1,
  '2859396_TGT_CTA': 1,
  '2859397_GT_TA': 1,
  '2859397_GT_CA': 1,
  '2859398_TGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCACCAAGTCGGTCAGCGCGGCATCGGCTGCTTCGCAGGCTAGTCGCAGCAGCGCCAGCTCGCCGGCGTCTTTAACCTCGCGCAGTGACTCCACAGTTCCGGATGCCCGCACCAACTCGGTGTTCTTGCCCTCCAGCGCGCCCGCCAAGGCGTCCAGGCCGTCCACCGTGACCACGTGGCTCTCGAAGCCCAGCTTTCCCACGCCGGCCTCGCCGGCCCGGCCGGCCAGGTAGCGCCCGACCGCGCGCTCGATAGCCACTTCGAGGTCGGGCGCTTGC_T': 1,
  '2859398_TGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCACCAAGTCGGTCAGCGCGGCATCGGCTGCTTCGCAGGCTAGTCGCAGCAGCGCC_T': 1,
  '2859399_GTC_CTA': 1,
  '2859399_GTC_TCA': 1,
  '2859399_GTC_TTA': 1,
  '2859400_TCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCACCAAGTCGGTCAGCGCGGC_T': 1,
  '2859402_CTC_TTA': 1,
  '2859402_CTC_TCA': 1,
  '2859404_C_A': 1,
  '2859405_GAT_TCA': 1,
  '2859405_GAT_TTA': 1,
  '2859405_GAT_CTA': 1,
  '2859407_TGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCC_T': 1,
  '2859408_GCG_TTA': 1,
  '2859408_GCG_CTA': 1,
  '2859408_GCG_TCA': 1,
  '2859409_CGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAAT_C': 1,
  '2859409_CG_C': 1,
  '2859410_GGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCA_G': 1,
  '2859411_GAC_TCA': 1,
  '2859411_GAC_TTA': 1,
  '2859411_GAC_CTA': 1,
  '2859414_AC_A': 1,
  '2859414_ACC_CTA': 1,
  '2859414_ACC_TCA': 1,
  '2859414_ACC_TTA': 1,
  '2859415_CCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCACCAAGTCGGTCAGCGCGGCATCGGCTGCTTCGCAGGCTAGTCGCAGCAGCGCCAGCTCGCCGGCGTCTTTAACCTCGCGCAGTGACTCCACAGTTCCGGATGCCCGCACCAACTCGGTGTTCTTGCCCTCCAGCGCGCCCGCCAAGGCGTCCAG_C': 1,
  '2859417_GCC_TTA': 1,
  '2859417_GCC_TCA': 1,
  '2859417_GCC_CTA': 1,
  '2859418_C_CCA': 1,
  '2859420_GCG_TTA': 1,
  '2859420_G_GAT': 1,
  '2859420_GCG_CTA': 1,
  '2859420_GCG_TCA': 1,
  '2859420_G_GT': 1,

In [ ]:
drug_dict = {}


for _, row in master_file.iterrows():
    snp = row["snp"]
    drug = row["drug"]
    grade = row["FINAL CONFIDENCE GRADING"]
    
    # Initialize nested dict if needed
    if snp not in drug_dict:
        drug_dict[snp] = {}
    
    # Initialize list if needed
    if drug not in drug_dict[snp]:
        drug_dict[snp][drug] = []
    
    # Append the grade
    drug_dict[snp][drug].append(grade)


drug_dict

{'2715344_GTG_ATA': {'Amikacin': ['2'], 'Kanamycin': ['1', '1']},
 '2715345_TG_CA': {'Amikacin': ['2'], 'Kanamycin': ['1']},
 '2715346_G_A': {'Amikacin': ['2'], 'Kanamycin': ['1']},
 '2715346_GGC_AGG': {'Amikacin': ['2'], 'Kanamycin': ['1']},
 '1473246_A_G': {'Amikacin': ['1'], 'Capreomycin': ['1'], 'Kanamycin': ['1']},
 '1473247_C_T': {'Amikacin': ['2'], 'Capreomycin': ['1'], 'Kanamycin': ['2']},
 '1473329_G_T': {'Amikacin': ['1'], 'Capreomycin': ['1'], 'Kanamycin': ['1']},
 '1461231_GCA_CCG': {'Bedaquiline': ['2']},
 '1461231_G_C': {'Bedaquiline': ['2']},
 '1461231_GCA_CCC': {'Bedaquiline': ['2']},
 '1461231_GCA_CCT': {'Bedaquiline': ['2']},
 '1461127_AC_CT': {'Bedaquiline': ['2']},
 '1461127_AC_CA': {'Bedaquiline': ['2']},
 '1461127_AC_CG': {'Bedaquiline': ['2']},
 '1461127_A_C': {'Bedaquiline': ['2']},
 '1461125_TGA_GGG': {'Bedaquiline': ['2']},
 '1461127_A_G': {'Bedaquiline': ['2']},
 '1461127_AC_GT': {'Bedaquiline': ['2']},
 '1461127_AC_GA': {'Bedaquiline': ['2']},
 '1461127_AC_GG': {'Bedaquiline': ['2']},
 '1461127_AC_TA': {'Bedaquiline': ['2']},
 '1461127_AC_TT': {'Bedaquiline': ['2']},
 '1461127_AC_TG': {'Bedaquiline': ['2']},
 '1461127_A_T': {'Bedaquiline': ['2']},
 '1461227_G_C': {'Bedaquiline': ['2']},
 '1461227_G_T': {'Bedaquiline': ['2']},
 '1461242_C_G': {'Bedaquiline': ['2']},
 '2859292_TGGGTCTCCTACAGAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAG_T': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859294_GGTCTCCTACAGAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACC_G': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859295_GTCTCCTACAGAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAG_G': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859303_CAGAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACA_C': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859303_CAG_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859303_CAG_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859303_CAG_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859304_AG_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859305_GAATGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCC_G': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859306_AAT_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859306_AAT_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859306_AAT_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859306_A_ATAACG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859308_TGGCCAGTTCTTTGGGGAACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGT_T': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859308_TG_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859309_GGC_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859309_GGC_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859309_G_GT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859309_GGC_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859310_G_GACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTC': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859312_CAG_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859312_CAG_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859313_AG_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859313_A_AG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859315_TTC_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859315_T_TCG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859316_TC_CA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859317_C_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859318_TTT_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859319_TT_CA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859320_T_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859321_GGG_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859321_GGG_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859321_GGG_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859324_GA_TC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859324_GA_CT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859324_GA_TT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859326_ACCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCACCAAGTCGGTCAGCGCGGCAT_A': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859327_CCG_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859327_CCGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACA_C': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859327_CCG_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859328_CG_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859328_CGGGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCAC_C': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859330_GGTCAACAATTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTG_G': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859330_GGT_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859330_GGT_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859330_GGT_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859332_TC_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859333_CA_TC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859333_CA_TT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859334_A_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859335_ACAATTCCGGGGTCTGCCCGGCG_A': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859336_CA_TT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859336_CA_TC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859337_A_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859337_AATTCCGG_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859339_TTCCGGGGTCTGCCCGGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCC_T': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859339_TTC_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859340_TC_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859340_TC_CA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859341_CCG_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859341_C_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859342_CGG_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859342_CGG_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859342_CGG_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859343_GG_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859345_GGT_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859345_GGTCT_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859345_GGT_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859345_G_GGC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859345_GGT_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859347_T_TGC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859348_C_CCGGCGCGG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859348_CTG_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859348_CTG_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859348_CT_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859348_CTG_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859349_TGC_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859350_G_GAT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859350_G_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859350_G_GATCCTGTC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859351_CCC_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859351_CCC_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859352_CC_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859353_CGG_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859354_GGC_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859354_G_GCGGGT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859354_GGC_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859354_GGCGGTTTCAGGCATTT_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859354_GGCGGTTTCAGGCAT_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859354_GGCGGTTTCAGGCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTC_G': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859354_GGC_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859355_GC_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859355_GCGGTTTCAGGC_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859356_C_CTGATGATGCT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859357_GGT_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859357_GGT_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859357_GGTTT_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859357_GGTTTC_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859357_GGT_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859357_GGTTTCAGGCATTTT_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859358_G_GA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859358_GT_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859359_T_TAC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859359_T_TAG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859359_TTTCA_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859359_T_TCCGC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859359_TTTCAGGC_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859359_TTTCAG_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859360_TTCAG_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859360_TTC_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859360_TTCAGGCATTTTCG_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859361_T_TCCCGC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859361_TC_CA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859362_C_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859362_C_CTG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859362_C_CG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859362_CAGGCA_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859363_AGG_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859363_AGG_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859363_AGG_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859363_AGGCATTTTCG_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859364_G_GCCGAGCTGTACCAGGCCGACCT': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859364_GGCATTTTC_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859365_GCATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGC_G': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859365_GCATT_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859366_CATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCA_C': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859366_CATTTTCGGCGTCCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCGGGCCACCAAGTCGGTCAGCGCGGCATCGGCTGCTTCGCAGGCTAGTCGCAGCAGCGCCAGCTCGCCGGCGTCTTTAACCTCGCGCAGTGACTCCACAGTTCCGGATGCCCGCACCAACTCGGTGTTCTTGCCCTCCAGCGCGCCCGCCAAGGCGTCCAGGCCGTCCACCGTGACCACGTGGCTCTCGAAGCCCAGCTTTCCCACGCCGGCCTCGCCGGCCCGGCCGGCCAGGTAGCGCCCGACCGCGCGCTCGATAGCCACTTCGAGGTCGGGCGCTTGCGAGGCGGCCTGAGTGCGGTACCGGCCGT_C': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859366_CAT_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859366_CATTTT_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859366_CATTT_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859366_CATTTTCGG_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859366_CAT_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859367_ATT_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859367_ATTTTC_GCCG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859367_ATTTTCGGCGTC_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859367_AT_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859368_TTTTCGGCGTC_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859368_T_TCGGCAGC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859368_TTTTCGGCG_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859369_TTTCGGCGTCC_T': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859369_TTT_CTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859370_T_TG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859370_TT_CA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859371_T_A': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859371_T_TC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859372_CG_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859372_CGG_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859372_CGG_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859372_C_CCG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859373_GGCGTC_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859373_GG_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859374_G_GC': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859374_GC_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859375_CG_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859375_CGT_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859375_CGT_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859375_CGT_C': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859376_GTC_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859376_GTCCC_G': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859376_GT_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859377_T_TTGTAGACG': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859378_CCCGCCAGCCACTACCAATGTGTCCTCGATGCGGACACCGCCGCGGCCGGGTAAATAGACACCGGGCTCCACGGTCACCACGGAGCCCGCCAGTAGTGTACCGGCGGATGTGACCCCGATGCCCGGCGCTTCATGTATCTGCAGGCCAACACCGTGTCCCAGTCCGTGACCGAAGTGCTCGCCGTAGCCGGCGTCGGCGATCAGCTGGCGCGCTGCAGCGTCCACCCCCCGCAGCTCGGCACCCGGCAGCAACGCCTGCCGACCGGCCTGTTGCGCCTCGGCCACCAGCTGATAGATCTCTAGCTGCCAGTCGGCGGCCTTGCCCAACACGAAGGTGCGGGTCATATCGGAGTGGTACCCGGCGACCAGGGCGCCGAAGTCGATCTTCACGAAATCGCCGACCTGCAGCACCGCGTCGGTCGGCCGGTGGTGCGGGATCGCCGAATTGGCCCCGGCAGCCACGATCGTCTCGAATGACACCGCGTCAGCGCCATGATCGAGCATCAGGGCCTCCAGCTCGCGGCTCACCTGCCGTTCGGTTCGGCCCGGCCGCAGGCCGCCGCG_C': {'Bedaquiline': ['2'],
  'Clofazimine': ['2']},
 '2859378_C_CT': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859378_CCC_TTA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859378_CCC_TCA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},
 '2859379_CC_TA': {'Bedaquiline': ['2'], 'Clofazimine': ['2']},

In [ ]:
final_dict = {"NC_000962.3": drug_dict}

json_str = json.dumps(final_dict)

with open(RESULTS/"snp-grading.json", "w") as f:
    f.write(json_str)

In [ ]:
weight_str = json.dumps(weight_dict)

with open(RESULTS/"weight_matrix.json", "w") as file:
    file.write(weight_str)

In [ ]:
for val in drug_dict.values():
    for grad in val.values():
        if len(grad) > 1:
            print(grad)

['1', '1']
['1', '2']
['1', '2']
['1', '2']
['1', '2']
['1', '1']
['1', '1']
['1', '1']
['2', '2']
['2', '1']
['2', '2', '2', '2']
['2', '2']
['2', '2']
['2', '2']
['1', '2']
['1', '2']
['1', '2']
['1', '2']
['2', '2']
['2', '2']
['2', '2']
['1', '2']
['1', '2']
['2', '2']
['1', '2']
['1', '2']
['2', '2']